services:
  moontracer:
    build: .
    image: moontracer:latest
    container_name: moontracer
    restart: unless-stopped
    secrets:
      - discord_bot_token
      - discord_guild_id
    environment:
      DB_PATH: /app/data/moontracer.db
      ADMIN_ROLE_NAME: ${ADMIN_ROLE_NAME}
      VERBOSE: "true"
    volumes:
      - /mnt/shared/suncaster/moontracer:/app/data
    networks:
      - caddy_proxy

networks:
  caddy_proxy:
    external: true

secrets:
  discord_bot_token:
    file: /mnt/shared/suncaster/moontracer/secrets/discord_bot_token.txt
  discord_guild_id:
    file: /mnt/shared/suncaster/moontracer/secrets/discord_guild_id.txt

